"""Tests for geneview.cli module (CLI subcommands and main entry point).

This module tests all CLI subcommands (manhattan, qq, venn, admixture) as well
as the shared CLI utilities and the main entry point.

Author: Shujia Huang
"""
import os
import sys
import tempfile
import shutil

import pytest
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from geneview.cli.main import main
from geneview.cli.utils import (
    get_figure_output_format,
    save_figure,
    add_common_figure_args,
    create_figure,
    resolve_output_path,
    parse_set_overrides,
    deep_merge,
)


# ---------------------------------------------------------------------------
# Paths to test data generated by examples/scripts/generate_test_data.py
# ---------------------------------------------------------------------------
_TEST_DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
_GWAS_FILE = os.path.join(_TEST_DATA_DIR, "gwas_example.assoc")
_VENN_DIR = os.path.join(_TEST_DATA_DIR, "venn_sets")
_VENN_FILES = [
    os.path.join(_VENN_DIR, "gene_list_%d.txt" % i) for i in range(1, 4)
]
_ADMIXTURE_DIR = os.path.join(_TEST_DATA_DIR, "admixture_example")
_ADMIXTURE_Q = os.path.join(_ADMIXTURE_DIR, "synthetic.Q")
_ADMIXTURE_POP = os.path.join(_ADMIXTURE_DIR, "synthetic_pop.txt")
_TRACKS_DIR = os.path.join(_TEST_DATA_DIR, "tracks_example")
_TRACKS_BED = os.path.join(_TRACKS_DIR, "annotations.bed")
_TRACKS_BEDGRAPH = os.path.join(_TRACKS_DIR, "coverage.bedgraph")
_TRACKS_GTF = os.path.join(_TRACKS_DIR, "gene_models.gtf")
_TRACKS_HIGHLIGHT = os.path.join(_TRACKS_DIR, "highlights.bed")


@pytest.fixture
def tmp_output_dir():
    """Create a temporary directory for output files; clean up after test."""
    d = tempfile.mkdtemp(prefix="geneview_cli_test_")
    yield d
    shutil.rmtree(d, ignore_errors=True)


# ===========================================================================
# Tests for CLI utility functions
# ===========================================================================
class TestGetFigureOutputFormat:
    """Tests for get_figure_output_format helper."""

    def test_png(self):
        assert get_figure_output_format("plot.png") == "png"

    def test_pdf(self):
        assert get_figure_output_format("plot.pdf") == "pdf"

    def test_svg(self):
        assert get_figure_output_format("plot.svg") == "svg"

    def test_eps(self):
        assert get_figure_output_format("output.eps") == "eps"

    def test_jpg(self):
        assert get_figure_output_format("fig.jpg") == "jpg"

    def test_uppercase_extension(self):
        assert get_figure_output_format("fig.PNG") == "png"

    def test_unknown_extension_defaults_to_png(self):
        assert get_figure_output_format("fig.xyz") == "png"

    def test_no_extension_defaults_to_png(self):
        assert get_figure_output_format("noext") == "png"

    def test_path_with_directory(self):
        assert get_figure_output_format("/tmp/output/fig.pdf") == "pdf"


class TestSaveFigure:
    """Tests for save_figure helper."""

    def test_save_png(self, tmp_output_dir):
        """Should save a figure to a PNG file."""
        fig, ax = plt.subplots()
        ax.plot([1, 2, 3])
        out_path = os.path.join(tmp_output_dir, "test.png")
        save_figure(fig, out_path, dpi=72)
        assert os.path.isfile(out_path)
        assert os.path.getsize(out_path) > 0

    def test_save_pdf(self, tmp_output_dir):
        """Should save a figure to a PDF file."""
        fig, ax = plt.subplots()
        ax.plot([1, 2, 3])
        out_path = os.path.join(tmp_output_dir, "test.pdf")
        save_figure(fig, out_path)
        assert os.path.isfile(out_path)

    def test_save_svg(self, tmp_output_dir):
        """Should save a figure to an SVG file."""
        fig, ax = plt.subplots()
        ax.plot([1, 2, 3])
        out_path = os.path.join(tmp_output_dir, "test.svg")
        save_figure(fig, out_path)
        assert os.path.isfile(out_path)


class TestCreateFigure:
    """Tests for create_figure helper."""

    def test_default_figsize(self):
        """Should create figure with default size when args.figsize is None."""
        import argparse
        args = argparse.Namespace(figsize=None, facecolor="w")
        fig, ax = create_figure(args, default_figsize=(10, 5))
        w, h = fig.get_size_inches()
        assert abs(w - 10) < 0.01
        assert abs(h - 5) < 0.01

    def test_custom_figsize(self):
        """Should use custom figure size from args."""
        import argparse
        args = argparse.Namespace(figsize=[8, 3], facecolor="w")
        fig, ax = create_figure(args)
        w, h = fig.get_size_inches()
        assert abs(w - 8) < 0.01
        assert abs(h - 3) < 0.01


class TestResolveOutputPath:
    """Tests for resolve_output_path helper."""

    def test_explicit_output(self):
        import argparse
        args = argparse.Namespace(output="my_plot.png")
        assert resolve_output_path(args, "default.png") == "my_plot.png"

    def test_default_output(self):
        import argparse
        args = argparse.Namespace(output=None)
        assert resolve_output_path(args, "default.png") == "default.png"


# ===========================================================================
# Tests for the main entry point
# ===========================================================================
class TestMainEntryPoint:
    """Tests for the CLI main() entry point."""

    def test_no_command_returns_1(self):
        """Should return exit code 1 when no subcommand is given."""
        result = main([])
        assert result == 1

    def test_version_flag(self):
        """Should print version and exit cleanly."""
        with pytest.raises(SystemExit) as exc_info:
            main(["--version"])
        assert exc_info.value.code == 0

    def test_help_flag(self):
        """Should print help and exit cleanly."""
        with pytest.raises(SystemExit) as exc_info:
            main(["--help"])
        assert exc_info.value.code == 0

    def test_unknown_command_returns_error(self):
        """Should return non-zero for unknown subcommand."""
        with pytest.raises(SystemExit):
            main(["nonexistent_command"])


# ===========================================================================
# Tests for the manhattan subcommand
# ===========================================================================
class TestManhattanCLI:
    """Tests for the ``geneview manhattan`` CLI subcommand."""

    @pytest.fixture(autouse=True)
    def _check_data(self):
        """Skip if test data is not available."""
        if not os.path.isfile(_GWAS_FILE):
            pytest.skip("Test GWAS data not found at %s" % _GWAS_FILE)

    def test_basic_run(self, tmp_output_dir):
        """Should create a manhattan plot with minimal arguments."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main(["manhattan", "-i", _GWAS_FILE, "-o", out])
        assert rc == 0
        assert os.path.isfile(out)

    def test_with_title_and_labels(self, tmp_output_dir):
        """Should accept title and axis label arguments."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--title", "Test GWAS",
            "--xlabel", "Chromosome",
            "--ylabel=P-value",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_with_significance_markers(self, tmp_output_dir):
        """Should accept significance marker arguments."""
        out = os.path.join(tmp_output_dir, "manhattan_sign.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--sign-marker-p", "1e-6",
            "--sign-marker-color", "r",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_annotate_topsnp(self, tmp_output_dir):
        """Should annotate top SNPs when --annotate-topsnp is set."""
        out = os.path.join(tmp_output_dir, "manhattan_anno.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--sign-marker-p", "1e-6",
            "--annotate-topsnp",
            "--ld-block-size", "100000",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_annotate_fmt_string(self, tmp_output_dir):
        """Should accept a format string for annotation labels."""
        out = os.path.join(tmp_output_dir, "manhattan_fmt.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--sign-marker-p", "1e-4", "--annotate-topsnp",
            "--annotate-fmt", "{snp}\nP={p:.1e}",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_annotate_layout_lane(self, tmp_output_dir):
        """Should support the tidy 'lane' annotation layout."""
        out = os.path.join(tmp_output_dir, "manhattan_lane.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--sign-marker-p", "1e-4", "--annotate-topsnp",
            "--annotate-layout", "lane", "--annotate-rotation", "90",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_annotate_no_arrow_and_color(self, tmp_output_dir):
        """Should support disabling arrows and setting label color."""
        out = os.path.join(tmp_output_dir, "manhattan_noarrow.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--sign-marker-p", "1e-4", "--annotate-topsnp",
            "--no-annotate-arrow", "--annotate-color", "navy",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_annotate_fmt_unknown_field_clear_error(self, tmp_output_dir):
        """An --annotate-fmt referencing an unknown field must fail early.

        Regression test: ``{gene}`` is not a valid label field, so the run
        must abort with a clear ValueError (surfaced as rc=1) *before* the
        plot is drawn, rather than blowing up with a cryptic KeyError.
        """
        out = os.path.join(tmp_output_dir, "manhattan_badfmt.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--sign-marker-p", "1e-4", "--annotate-topsnp",
            "--annotate-fmt", "{gene}",
        ])
        assert rc == 1
        assert not os.path.isfile(out)

    def test_annotate_fmt_bad_spec_clear_error(self, tmp_output_dir):
        """An --annotate-fmt with an invalid format spec must fail early."""
        out = os.path.join(tmp_output_dir, "manhattan_badspec.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--sign-marker-p", "1e-4", "--annotate-topsnp",
            "--annotate-fmt", "{p:qq}",
        ])
        assert rc == 1
        assert not os.path.isfile(out)

    def test_nonexistent_chromosome_clear_error(self, tmp_output_dir):
        """--chr with a missing chromosome should fail with a clear message."""
        out = os.path.join(tmp_output_dir, "manhattan_bad.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--chr", "chrDoesNotExist",
        ])
        assert rc == 1
        assert not os.path.isfile(out)

    def test_annotate_fmt_decodes_literal_newline(self, tmp_output_dir):
        """A literal '\\n' typed in the shell must render as a real line break.

        Regression test: single-quoted shell args keep backslash-n as two
        characters, which would otherwise appear verbatim in the label.
        """
        out = os.path.join(tmp_output_dir, "manhattan_nl.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--sign-marker-p", "1e-4", "--annotate-topsnp",
            "--annotate-fmt", r"{snp}\nP={p:.1e}",  # literal backslash-n
        ])
        assert rc == 0
        texts = [t.get_text() for t in plt.gcf().axes[0].texts]
        plt.close("all")
        # No label may contain the literal two-character backslash-n ...
        assert all("\\n" not in t for t in texts)
        # ... and at least one label must contain a real newline.
        assert any("\n" in t for t in texts)

    def test_set_overrides_reach_engine(self, tmp_output_dir):
        """--set should forward nested kwargs (e.g. adjust_text_kws, scatter s)."""
        out = os.path.join(tmp_output_dir, "manhattan_set.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--sign-marker-p", "1e-4", "--annotate-topsnp",
            "--set", "adjust_text_kws.lim=300",
            "--set", "adjust_text_kws.force_text=0.5,0.8",
            "--set", "s=25",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_set_invalid_raises(self, tmp_output_dir):
        """A malformed --set value should produce a non-zero exit code."""
        out = os.path.join(tmp_output_dir, "manhattan_badset.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--set", "noequalsign",
        ])
        assert rc == 1

    def test_custom_figsize(self, tmp_output_dir):
        """Should accept custom figure size."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--figsize", "16", "5",
        ])
        assert rc == 0

    def test_xtick_rotation(self, tmp_output_dir):
        """Should accept x-tick rotation."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--xtick-rotation", "45",
        ])
        assert rc == 0

    def test_specific_chromosome(self, tmp_output_dir):
        """Should plot only a specific chromosome with --chr."""
        out = os.path.join(tmp_output_dir, "manhattan_chr1.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--chr", "chr1",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_no_logp(self, tmp_output_dir):
        """Should work with --no-logp flag."""
        out = os.path.join(tmp_output_dir, "manhattan_raw.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--no-logp",
        ])
        assert rc == 0

    def test_disable_significance_lines(self, tmp_output_dir):
        """Setting thresholds to 0 should disable significance lines."""
        out = os.path.join(tmp_output_dir, "manhattan_nolines.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--suggestiveline", "0",
            "--genomewideline", "0",
        ])
        assert rc == 0

    def test_default_output_name(self, tmp_output_dir):
        """Should default to manhattan.png when -o is not given."""
        original_dir = os.getcwd()
        os.chdir(tmp_output_dir)
        try:
            rc = main(["manhattan", "-i", _GWAS_FILE])
            assert rc == 0
            assert os.path.isfile(os.path.join(tmp_output_dir, "manhattan.png"))
        finally:
            os.chdir(original_dir)

    def test_invalid_input_file(self, tmp_output_dir):
        """Should return error for non-existent input file."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main(["manhattan", "-i", "nonexistent_file.tsv", "-o", out])
        assert rc == 1

    def test_missing_input_flag(self):
        """Should fail when -i is not provided."""
        with pytest.raises(SystemExit):
            main(["manhattan"])

    def test_pdf_output(self, tmp_output_dir):
        """Should save to PDF format."""
        out = os.path.join(tmp_output_dir, "manhattan.pdf")
        rc = main(["manhattan", "-i", _GWAS_FILE, "-o", out])
        assert rc == 0
        assert os.path.isfile(out)

    def test_xtick_labels(self, tmp_output_dir):
        """Should accept custom x-tick labels."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--xtick-labels", "chr1", "chr3", "chr5",
        ])
        assert rc == 0

    def test_custom_color_and_alpha(self, tmp_output_dir):
        """Should accept custom color and alpha."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--color", "#FF0000,#00FF00",
            "--alpha", "0.5",
        ])
        assert rc == 0


# ===========================================================================
# Tests for the qq subcommand
# ===========================================================================
class TestQqCLI:
    """Tests for the ``geneview qq`` CLI subcommand."""

    @pytest.fixture(autouse=True)
    def _check_data(self):
        """Skip if test data is not available."""
        if not os.path.isfile(_GWAS_FILE):
            pytest.skip("Test GWAS data not found at %s" % _GWAS_FILE)

    def test_basic_run(self, tmp_output_dir):
        """Should create a QQ plot with minimal arguments."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main(["qq", "-i", _GWAS_FILE, "-o", out])
        assert rc == 0
        assert os.path.isfile(out)

    def test_with_title(self, tmp_output_dir):
        """Should accept a custom title."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--title", "Test QQ ",
        ])
        assert rc == 0

    def test_custom_labels(self, tmp_output_dir):
        """Should accept custom x and y labels."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--xlabel", "Expected",
            "--ylabel", "Observed",
        ])
        assert rc == 0

    def test_no_logp(self, tmp_output_dir):
        """Should work with --no-logp."""
        out = os.path.join(tmp_output_dir, "qq_raw.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--no-logp",
        ])
        assert rc == 0

    def test_no_abline(self, tmp_output_dir):
        """Should disable reference line with --ablinecolor none."""
        out = os.path.join(tmp_output_dir, "qq_noab.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--ablinecolor", "none",
        ])
        assert rc == 0

    def test_custom_marker_and_color(self, tmp_output_dir):
        """Should accept custom marker and color."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--marker", "s",
            "--color", "blue",
        ])
        assert rc == 0

    def test_custom_figsize(self, tmp_output_dir):
        """Should accept custom figure size."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--figsize", "8", "8",
        ])
        assert rc == 0

    def test_default_output_name(self, tmp_output_dir):
        """Should default to qq.png when -o is not given."""
        original_dir = os.getcwd()
        os.chdir(tmp_output_dir)
        try:
            rc = main(["qq", "-i", _GWAS_FILE])
            assert rc == 0
            assert os.path.isfile(os.path.join(tmp_output_dir, "qq.png"))
        finally:
            os.chdir(original_dir)

    def test_invalid_input_file(self, tmp_output_dir):
        """Should return error for non-existent input file."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main(["qq", "-i", "nonexistent_file.tsv", "-o", out])
        assert rc == 1

    def test_missing_pv_column(self, tmp_output_dir):
        """Should return error when p-value column doesn't exist."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--pv", "NONEXISTENT_COL",
        ])
        assert rc == 1

    def test_missing_input_flag(self):
        """Should fail when -i is not provided."""
        with pytest.raises(SystemExit):
            main(["qq"])


# ===========================================================================
# Tests for the venn subcommand
# ===========================================================================
class TestVennCLI:
    """Tests for the ``geneview venn`` CLI subcommand."""

    @pytest.fixture(autouse=True)
    def _check_data(self):
        """Skip if test data is not available."""
        if not all(os.path.isfile(f) for f in _VENN_FILES):
            pytest.skip("Test Venn data not found in %s" % _VENN_DIR)

    def test_basic_2_sets(self, tmp_output_dir):
        """Should create a 2-set Venn diagram."""
        out = os.path.join(tmp_output_dir, "venn2.png")
        rc = main(["venn", "-i", _VENN_FILES[0], _VENN_FILES[1], "-o", out])
        assert rc == 0
        assert os.path.isfile(out)

    def test_basic_3_sets(self, tmp_output_dir):
        """Should create a 3-set Venn diagram."""
        out = os.path.join(tmp_output_dir, "venn3.png")
        rc = main(["venn", "-i"] + _VENN_FILES + ["-o", out])
        assert rc == 0
        assert os.path.isfile(out)

    def test_custom_names(self, tmp_output_dir):
        """Should accept custom dataset names."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--names", "Alpha", "Beta",
        ])
        assert rc == 0

    def test_custom_palette(self, tmp_output_dir):
        """Should accept custom palette."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--palette", "plasma",
        ])
        assert rc == 0

    def test_custom_fmt(self, tmp_output_dir):
        """Should accept custom format string for petal labels."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--fmt", "{size}\n({percentage:.0f}%)",
        ])
        assert rc == 0

    def test_legend_use_petal_color(self, tmp_output_dir):
        """Should accept --legend-use-petal-color flag."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--legend-use-petal-color",
        ])
        assert rc == 0

    def test_legend_loc(self, tmp_output_dir):
        """Should accept --legend-loc argument."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--legend-loc", "upper left",
        ])
        assert rc == 0

    def test_too_few_files(self, tmp_output_dir):
        """Should fail with fewer than 2 input files."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main(["venn", "-i", _VENN_FILES[0], "-o", out])
        assert rc == 1

    def test_nonexistent_file(self, tmp_output_dir):
        """Should fail for non-existent input files."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], "nonexistent.txt",
            "-o", out,
        ])
        assert rc == 1

    def test_default_output_name(self, tmp_output_dir):
        """Should default to venn.png when -o is not given."""
        original_dir = os.getcwd()
        os.chdir(tmp_output_dir)
        try:
            rc = main(["venn", "-i", _VENN_FILES[0], _VENN_FILES[1]])
            assert rc == 0
            assert os.path.isfile(os.path.join(tmp_output_dir, "venn.png"))
        finally:
            os.chdir(original_dir)

    def test_missing_input_flag(self):
        """Should fail when -i is not provided."""
        with pytest.raises(SystemExit):
            main(["venn"])

    def test_custom_fontsize_and_alpha(self, tmp_output_dir):
        """Should accept custom fontsize and alpha."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--fontsize", "16",
            "--alpha", "0.6",
        ])
        assert rc == 0


# ===========================================================================
# Tests for the admixture subcommand
# ===========================================================================
class TestAdmixtureCLI:
    """Tests for the ``geneview admixture`` CLI subcommand."""

    @pytest.fixture(autouse=True)
    def _check_data(self):
        """Skip if test data is not available."""
        if not os.path.isfile(_ADMIXTURE_Q) or not os.path.isfile(_ADMIXTURE_POP):
            pytest.skip("Test admixture data not found in %s" % _ADMIXTURE_DIR)

    def test_basic_run(self, tmp_output_dir):
        """Should create an admixture plot with minimal arguments."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_custom_palette(self, tmp_output_dir):
        """Should accept a custom palette."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--palette", "Set1",
        ])
        assert rc == 0

    def test_group_order(self, tmp_output_dir):
        """Should accept a custom group order."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--group-order", "POP4", "POP3", "POP2", "POP1",
        ])
        assert rc == 0

    def test_set_xticklabel_top(self, tmp_output_dir):
        """Should place labels at top with --set-xticklabel-top."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--set-xticklabel-top",
        ])
        assert rc == 0

    def test_xtick_rotation(self, tmp_output_dir):
        """Should accept x-tick label rotation."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--xtick-rotation", "45",
        ])
        assert rc == 0

    def test_edgewidth_and_linewidth(self, tmp_output_dir):
        """Should accept custom edge and line widths."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--edgewidth", "2.0",
            "--linewidth", "0.5",
        ])
        assert rc == 0

    def test_shuffle_frac(self, tmp_output_dir):
        """Should sample a fraction of each population."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--shuffle-frac", "0.5",
        ])
        assert rc == 0

    def test_shuffle_n(self, tmp_output_dir):
        """Should sample N individuals per population."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--shuffle-n", "10",
        ])
        assert rc == 0

    def test_custom_ylabel(self, tmp_output_dir):
        """Should accept a custom y-axis label."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--ylabel", "K=3 custom",
        ])
        assert rc == 0

    def test_default_output_name(self, tmp_output_dir):
        """Should default to admixture.png when -o is not given."""
        original_dir = os.getcwd()
        os.chdir(tmp_output_dir)
        try:
            rc = main([
                "admixture", "-i", _ADMIXTURE_Q,
                "-p", _ADMIXTURE_POP,
            ])
            assert rc == 0
            assert os.path.isfile(os.path.join(tmp_output_dir, "admixture.png"))
        finally:
            os.chdir(original_dir)

    def test_invalid_input_file(self, tmp_output_dir):
        """Should return error for non-existent input file."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", "nonexistent.Q",
            "-p", _ADMIXTURE_POP, "-o", out,
        ])
        assert rc == 1

    def test_missing_required_flags(self):
        """Should fail when required flags are missing."""
        with pytest.raises(SystemExit):
            main(["admixture"])
        with pytest.raises(SystemExit):
            main(["admixture", "-i", _ADMIXTURE_Q])
        with pytest.raises(SystemExit):
            main(["admixture", "-p", _ADMIXTURE_POP])

    def test_custom_figsize(self, tmp_output_dir):
        """Should accept custom figure size."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--figsize", "16", "3",
        ])
        assert rc == 0


# ===========================================================================
# Tests for the tracks subcommand
# ===========================================================================
class TestTracksCLI:
    """Tests for the ``geneview tracks`` CLI subcommand."""

    @pytest.fixture(autouse=True)
    def _check_data(self):
        """Skip if test data is not available."""
        if not os.path.isfile(_TRACKS_BED):
            pytest.skip("Test tracks data not found in %s" % _TRACKS_DIR)

    def test_basic_axis_only(self, tmp_output_dir):
        """Should create a plot with just the genome axis."""
        out = os.path.join(tmp_output_dir, "tracks_axis.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_with_annotation(self, tmp_output_dir):
        """Should create a plot with an annotation track."""
        out = os.path.join(tmp_output_dir, "tracks_anno.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-a", _TRACKS_BED,
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_with_data_track(self, tmp_output_dir):
        """Should create a plot with a data track."""
        out = os.path.join(tmp_output_dir, "tracks_data.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-d", _TRACKS_BEDGRAPH,
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_with_gene_region(self, tmp_output_dir):
        """Should create a plot with a gene region track."""
        out = os.path.join(tmp_output_dir, "tracks_gene.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-g", _TRACKS_GTF,
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_with_highlight(self, tmp_output_dir):
        """Should create a plot with highlight regions."""
        out = os.path.join(tmp_output_dir, "tracks_hl.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-a", _TRACKS_BED,
            "-d", _TRACKS_BEDGRAPH,
            "--highlight", _TRACKS_HIGHLIGHT,
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_custom_data_type(self, tmp_output_dir):
        """Should accept --data-type line."""
        out = os.path.join(tmp_output_dir, "tracks_line.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-d", _TRACKS_BEDGRAPH,
            "--data-type", "line",
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_region_with_m_suffix(self, tmp_output_dir):
        """Should parse region with M/m suffix."""
        out = os.path.join(tmp_output_dir, "tracks_m.png")
        rc = main([
            "tracks", "--region", "chr7:26M-27M",
            "-d", _TRACKS_BEDGRAPH,
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_no_axis_flag(self, tmp_output_dir):
        """Should disable genome axis with --no-axis."""
        out = os.path.join(tmp_output_dir, "tracks_noaxis.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "--no-axis",
            "-a", _TRACKS_BED,
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_annotation_shape(self, tmp_output_dir):
        """Should accept --annotation-shape box."""
        out = os.path.join(tmp_output_dir, "tracks_box.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-a", _TRACKS_BED,
            "--annotation-shape", "box",
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_custom_figsize(self, tmp_output_dir):
        """Should accept custom figure size."""
        out = os.path.join(tmp_output_dir, "tracks.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-d", _TRACKS_BEDGRAPH,
            "-o", out,
            "--figsize", "16", "5",
        ])
        assert rc == 0

    def test_invalid_region(self, tmp_output_dir):
        """Should return error for malformed region string."""
        out = os.path.join(tmp_output_dir, "tracks.png")
        rc = main([
            "tracks", "--region", "invalid_region",
            "-o", out,
        ])
        assert rc == 1

    def test_invalid_region_reversed(self, tmp_output_dir):
        """Should return error when start >= end."""
        out = os.path.join(tmp_output_dir, "tracks.png")
        rc = main([
            "tracks", "--region", "chr7:60000000-20000000",
            "-o", out,
        ])
        assert rc == 1

    def test_missing_region_flag(self):
        """Should fail when --region is not provided."""
        with pytest.raises(SystemExit):
            main(["tracks", "-a", _TRACKS_BED])

    def test_default_output_name(self, tmp_output_dir):
        """Should default to genome_tracks.png when -o is not given."""
        original_dir = os.getcwd()
        os.chdir(tmp_output_dir)
        try:
            rc = main([
                "tracks", "--region", "chr7:26490000-26720000",
                "-a", _TRACKS_BED,
            ])
            assert rc == 0
            assert os.path.isfile(os.path.join(tmp_output_dir, "genome_tracks.png"))
        finally:
            os.chdir(original_dir)

    def test_nonexistent_annotation_file(self, tmp_output_dir):
        """Should return error for non-existent annotation file."""
        out = os.path.join(tmp_output_dir, "tracks.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-a", "nonexistent.bed",
            "-o", out,
        ])
        assert rc == 1

    def test_multiple_tracks(self, tmp_output_dir):
        """Should handle multiple track types together."""
        out = os.path.join(tmp_output_dir, "tracks_multi.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-a", _TRACKS_BED,
            "-g", _TRACKS_GTF,
            "-d", _TRACKS_BEDGRAPH,
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_collapse_transcripts(self, tmp_output_dir):
        """Should accept --collapse-transcripts meta."""
        out = os.path.join(tmp_output_dir, "tracks_meta.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-g", _TRACKS_GTF,
            "--collapse-transcripts", "meta",
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_highlight_custom_colors(self, tmp_output_dir):
        """Should accept custom highlight fill and alpha."""
        out = os.path.join(tmp_output_dir, "tracks_hlcustom.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-d", _TRACKS_BEDGRAPH,
            "--highlight", _TRACKS_HIGHLIGHT,
            "--highlight-fill", "#FFE3E6",
            "--highlight-alpha", "0.5",
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_data_color(self, tmp_output_dir):
        """Should accept --data-color."""
        out = os.path.join(tmp_output_dir, "tracks_dcolor.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-d", _TRACKS_BEDGRAPH,
            "--data-color", "red",
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_track_names(self, tmp_output_dir):
        """Should accept custom track names."""
        out = os.path.join(tmp_output_dir, "tracks_names.png")
        rc = main([
            "tracks", "--region", "chr7:26490000-26720000",
            "-a", _TRACKS_BED,
            "-d", _TRACKS_BEDGRAPH,
            "--annotation-name", "CpG",
            "--data-name", "Signal",
            "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)


# ===========================================================================
# Tests for --set parsing utilities
# ===========================================================================
class TestParseSetOverrides:
    """Unit tests for parse_set_overrides() and deep_merge()."""

    def test_flat_key(self):
        assert parse_set_overrides(["s=25"]) == {"s": 25}

    def test_nested_dotted_key(self):
        out = parse_set_overrides(["adjust_text_kws.lim=300"])
        assert out == {"adjust_text_kws": {"lim": 300}}

    def test_comma_list_becomes_tuple(self):
        out = parse_set_overrides(["adjust_text_kws.force_text=0.5,0.8"])
        assert out == {"adjust_text_kws": {"force_text": (0.5, 0.8)}}

    def test_scalar_type_coercion(self):
        out = parse_set_overrides([
            "a=1", "b=1.5", "c=true", "d=false", "e=none", "f=hello",
        ])
        assert out == {"a": 1, "b": 1.5, "c": True, "d": False,
                       "e": None, "f": "hello"}

    def test_json_container(self):
        out = parse_set_overrides(['adjust_text_kws.only_move={"points":"y"}'])
        assert out == {"adjust_text_kws": {"only_move": {"points": "y"}}}

    def test_multiple_same_root_merges(self):
        out = parse_set_overrides([
            "adjust_text_kws.lim=300",
            "adjust_text_kws.precision=0.01",
        ])
        assert out == {"adjust_text_kws": {"lim": 300, "precision": 0.01}}

    def test_missing_equals_raises(self):
        with pytest.raises(ValueError, match="KEY=VALUE"):
            parse_set_overrides(["noequalsign"])

    def test_empty_key_raises(self):
        with pytest.raises(ValueError, match="empty KEY"):
            parse_set_overrides(["=5"])

    def test_deep_merge_nested(self):
        base = {"fontsize": 12, "arrowprops": {"color": "k", "lw": 0.6}}
        deep_merge(base, {"arrowprops": {"color": "red"}, "rotation": 90})
        assert base == {"fontsize": 12, "rotation": 90,
                        "arrowprops": {"color": "red", "lw": 0.6}}

    def test_deep_merge_overwrite_non_dict(self):
        base = {"a": {"x": 1}}
        deep_merge(base, {"a": 5})
        assert base == {"a": 5}


# ===========================================================================
# Tests for the main() exit-code contract
# ===========================================================================
class TestMainReturnCode:
    """main() must propagate a subcommand run()'s integer exit code."""

    def test_run_returning_1_propagates(self, monkeypatch, tmp_output_dir):
        """A run() that returns 1 must make main() return 1 (not 0)."""
        import geneview.cli.tracks as tracks_mod
        monkeypatch.setattr(tracks_mod, "run", lambda args: 1)
        rc = main(["tracks", "--region", "chr1:1-1000",
                   "-o", os.path.join(tmp_output_dir, "x.png")])
        assert rc == 1

    def test_run_returning_none_means_success(self, monkeypatch, tmp_output_dir):
        """A run() that returns None must make main() return 0."""
        import geneview.cli.tracks as tracks_mod
        monkeypatch.setattr(tracks_mod, "run", lambda args: None)
        rc = main(["tracks", "--region", "chr1:1-1000",
                   "-o", os.path.join(tmp_output_dir, "x.png")])
        assert rc == 0

    def test_run_raising_returns_1(self, monkeypatch, tmp_output_dir):
        """A run() that raises must make main() return 1."""
        import geneview.cli.tracks as tracks_mod
        def _boom(args):
            raise RuntimeError("plot failed")
        monkeypatch.setattr(tracks_mod, "run", _boom)
        rc = main(["tracks", "--region", "chr1:1-1000",
                   "-o", os.path.join(tmp_output_dir, "x.png")])
        assert rc == 1


class TestDebugFlag:
    """The global --debug flag controls traceback vs. short-message behaviour."""

    def test_debug_reraises_traceback(self, monkeypatch, tmp_output_dir):
        """With --debug, a failing run() re-raises instead of returning 1."""
        import geneview.cli.tracks as tracks_mod

        def _boom(args):
            raise RuntimeError("plot failed")
        monkeypatch.setattr(tracks_mod, "run", _boom)
        with pytest.raises(RuntimeError, match="plot failed"):
            main(["--debug", "tracks", "--region", "chr1:1-1000",
                  "-o", os.path.join(tmp_output_dir, "x.png")])

    def test_without_debug_returns_1_and_hint(self, monkeypatch, tmp_output_dir, capsys):
        """Without --debug, a failing run() returns 1 and prints a hint."""
        import geneview.cli.tracks as tracks_mod

        def _boom(args):
            raise RuntimeError("plot failed")
        monkeypatch.setattr(tracks_mod, "run", _boom)
        rc = main(["tracks", "--region", "chr1:1-1000",
                   "-o", os.path.join(tmp_output_dir, "x.png")])
        assert rc == 1
        err = capsys.readouterr().err
        assert "[ERROR] plot failed" in err
        assert "--debug" in err
