"""Tests for geneview.cli module (CLI subcommands and main entry point).

This module tests all CLI subcommands (manhattan, qq, venn, admixture) as well
as the shared CLI utilities and the main entry point.

Author: Shujia Huang
"""
import os
import sys
import tempfile
import shutil

import pytest
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from geneview.cli.main import main
from geneview.cli.utils import (
    get_figure_output_format,
    save_figure,
    add_common_figure_args,
    create_figure,
    resolve_output_path,
)


# ---------------------------------------------------------------------------
# Paths to test data generated by examples/scripts/generate_test_data.py
# ---------------------------------------------------------------------------
_TEST_DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
_GWAS_FILE = os.path.join(_TEST_DATA_DIR, "gwas_example.assoc")
_VENN_DIR = os.path.join(_TEST_DATA_DIR, "venn_sets")
_VENN_FILES = [
    os.path.join(_VENN_DIR, "gene_list_%d.txt" % i) for i in range(1, 4)
]
_ADMIXTURE_DIR = os.path.join(_TEST_DATA_DIR, "admixture_example")
_ADMIXTURE_Q = os.path.join(_ADMIXTURE_DIR, "synthetic.Q")
_ADMIXTURE_POP = os.path.join(_ADMIXTURE_DIR, "synthetic_pop.txt")


@pytest.fixture
def tmp_output_dir():
    """Create a temporary directory for output files; clean up after test."""
    d = tempfile.mkdtemp(prefix="geneview_cli_test_")
    yield d
    shutil.rmtree(d, ignore_errors=True)


# ===========================================================================
# Tests for CLI utility functions
# ===========================================================================
class TestGetFigureOutputFormat:
    """Tests for get_figure_output_format helper."""

    def test_png(self):
        assert get_figure_output_format("plot.png") == "png"

    def test_pdf(self):
        assert get_figure_output_format("plot.pdf") == "pdf"

    def test_svg(self):
        assert get_figure_output_format("plot.svg") == "svg"

    def test_eps(self):
        assert get_figure_output_format("output.eps") == "eps"

    def test_jpg(self):
        assert get_figure_output_format("fig.jpg") == "jpg"

    def test_uppercase_extension(self):
        assert get_figure_output_format("fig.PNG") == "png"

    def test_unknown_extension_defaults_to_png(self):
        assert get_figure_output_format("fig.xyz") == "png"

    def test_no_extension_defaults_to_png(self):
        assert get_figure_output_format("noext") == "png"

    def test_path_with_directory(self):
        assert get_figure_output_format("/tmp/output/fig.pdf") == "pdf"


class TestSaveFigure:
    """Tests for save_figure helper."""

    def test_save_png(self, tmp_output_dir):
        """Should save a figure to a PNG file."""
        fig, ax = plt.subplots()
        ax.plot([1, 2, 3])
        out_path = os.path.join(tmp_output_dir, "test.png")
        save_figure(fig, out_path, dpi=72)
        assert os.path.isfile(out_path)
        assert os.path.getsize(out_path) > 0

    def test_save_pdf(self, tmp_output_dir):
        """Should save a figure to a PDF file."""
        fig, ax = plt.subplots()
        ax.plot([1, 2, 3])
        out_path = os.path.join(tmp_output_dir, "test.pdf")
        save_figure(fig, out_path)
        assert os.path.isfile(out_path)

    def test_save_svg(self, tmp_output_dir):
        """Should save a figure to an SVG file."""
        fig, ax = plt.subplots()
        ax.plot([1, 2, 3])
        out_path = os.path.join(tmp_output_dir, "test.svg")
        save_figure(fig, out_path)
        assert os.path.isfile(out_path)


class TestCreateFigure:
    """Tests for create_figure helper."""

    def test_default_figsize(self):
        """Should create figure with default size when args.figsize is None."""
        import argparse
        args = argparse.Namespace(figsize=None, facecolor="w")
        fig, ax = create_figure(args, default_figsize=(10, 5))
        w, h = fig.get_size_inches()
        assert abs(w - 10) < 0.01
        assert abs(h - 5) < 0.01

    def test_custom_figsize(self):
        """Should use custom figure size from args."""
        import argparse
        args = argparse.Namespace(figsize=[8, 3], facecolor="w")
        fig, ax = create_figure(args)
        w, h = fig.get_size_inches()
        assert abs(w - 8) < 0.01
        assert abs(h - 3) < 0.01


class TestResolveOutputPath:
    """Tests for resolve_output_path helper."""

    def test_explicit_output(self):
        import argparse
        args = argparse.Namespace(output="my_plot.png")
        assert resolve_output_path(args, "default.png") == "my_plot.png"

    def test_default_output(self):
        import argparse
        args = argparse.Namespace(output=None)
        assert resolve_output_path(args, "default.png") == "default.png"


# ===========================================================================
# Tests for the main entry point
# ===========================================================================
class TestMainEntryPoint:
    """Tests for the CLI main() entry point."""

    def test_no_command_returns_1(self):
        """Should return exit code 1 when no subcommand is given."""
        result = main([])
        assert result == 1

    def test_version_flag(self):
        """Should print version and exit cleanly."""
        with pytest.raises(SystemExit) as exc_info:
            main(["--version"])
        assert exc_info.value.code == 0

    def test_help_flag(self):
        """Should print help and exit cleanly."""
        with pytest.raises(SystemExit) as exc_info:
            main(["--help"])
        assert exc_info.value.code == 0

    def test_unknown_command_returns_error(self):
        """Should return non-zero for unknown subcommand."""
        with pytest.raises(SystemExit):
            main(["nonexistent_command"])


# ===========================================================================
# Tests for the manhattan subcommand
# ===========================================================================
class TestManhattanCLI:
    """Tests for the ``geneview manhattan`` CLI subcommand."""

    @pytest.fixture(autouse=True)
    def _check_data(self):
        """Skip if test data is not available."""
        if not os.path.isfile(_GWAS_FILE):
            pytest.skip("Test GWAS data not found at %s" % _GWAS_FILE)

    def test_basic_run(self, tmp_output_dir):
        """Should create a manhattan plot with minimal arguments."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main(["manhattan", "-i", _GWAS_FILE, "-o", out])
        assert rc == 0
        assert os.path.isfile(out)

    def test_with_title_and_labels(self, tmp_output_dir):
        """Should accept title and axis label arguments."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--title", "Test GWAS",
            "--xlabel", "Chromosome",
            "--ylabel=P-value",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_with_significance_markers(self, tmp_output_dir):
        """Should accept significance marker arguments."""
        out = os.path.join(tmp_output_dir, "manhattan_sign.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--sign-marker-p", "1e-6",
            "--sign-marker-color", "r",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_annotate_topsnp(self, tmp_output_dir):
        """Should annotate top SNPs when --annotate-topsnp is set."""
        out = os.path.join(tmp_output_dir, "manhattan_anno.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--sign-marker-p", "1e-6",
            "--annotate-topsnp",
            "--ld-block-size", "100000",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_custom_figsize(self, tmp_output_dir):
        """Should accept custom figure size."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--figsize", "16", "5",
        ])
        assert rc == 0

    def test_xtick_rotation(self, tmp_output_dir):
        """Should accept x-tick rotation."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--xtick-rotation", "45",
        ])
        assert rc == 0

    def test_specific_chromosome(self, tmp_output_dir):
        """Should plot only a specific chromosome with --chr."""
        out = os.path.join(tmp_output_dir, "manhattan_chr1.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--chr", "chr1",
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_no_logp(self, tmp_output_dir):
        """Should work with --no-logp flag."""
        out = os.path.join(tmp_output_dir, "manhattan_raw.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--no-logp",
        ])
        assert rc == 0

    def test_disable_significance_lines(self, tmp_output_dir):
        """Setting thresholds to 0 should disable significance lines."""
        out = os.path.join(tmp_output_dir, "manhattan_nolines.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--suggestiveline", "0",
            "--genomewideline", "0",
        ])
        assert rc == 0

    def test_default_output_name(self, tmp_output_dir):
        """Should default to manhattan.png when -o is not given."""
        original_dir = os.getcwd()
        os.chdir(tmp_output_dir)
        try:
            rc = main(["manhattan", "-i", _GWAS_FILE])
            assert rc == 0
            assert os.path.isfile(os.path.join(tmp_output_dir, "manhattan.png"))
        finally:
            os.chdir(original_dir)

    def test_invalid_input_file(self, tmp_output_dir):
        """Should return error for non-existent input file."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main(["manhattan", "-i", "nonexistent_file.tsv", "-o", out])
        assert rc == 1

    def test_missing_input_flag(self):
        """Should fail when -i is not provided."""
        with pytest.raises(SystemExit):
            main(["manhattan"])

    def test_pdf_output(self, tmp_output_dir):
        """Should save to PDF format."""
        out = os.path.join(tmp_output_dir, "manhattan.pdf")
        rc = main(["manhattan", "-i", _GWAS_FILE, "-o", out])
        assert rc == 0
        assert os.path.isfile(out)

    def test_xtick_labels(self, tmp_output_dir):
        """Should accept custom x-tick labels."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--xtick-labels", "chr1", "chr3", "chr5",
        ])
        assert rc == 0

    def test_custom_color_and_alpha(self, tmp_output_dir):
        """Should accept custom color and alpha."""
        out = os.path.join(tmp_output_dir, "manhattan.png")
        rc = main([
            "manhattan", "-i", _GWAS_FILE, "-o", out,
            "--color", "#FF0000,#00FF00",
            "--alpha", "0.5",
        ])
        assert rc == 0


# ===========================================================================
# Tests for the qq subcommand
# ===========================================================================
class TestQqCLI:
    """Tests for the ``geneview qq`` CLI subcommand."""

    @pytest.fixture(autouse=True)
    def _check_data(self):
        """Skip if test data is not available."""
        if not os.path.isfile(_GWAS_FILE):
            pytest.skip("Test GWAS data not found at %s" % _GWAS_FILE)

    def test_basic_run(self, tmp_output_dir):
        """Should create a QQ plot with minimal arguments."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main(["qq", "-i", _GWAS_FILE, "-o", out])
        assert rc == 0
        assert os.path.isfile(out)

    def test_with_title(self, tmp_output_dir):
        """Should accept a custom title."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--title", "Test QQ ",
        ])
        assert rc == 0

    def test_custom_labels(self, tmp_output_dir):
        """Should accept custom x and y labels."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--xlabel", "Expected",
            "--ylabel", "Observed",
        ])
        assert rc == 0

    def test_no_logp(self, tmp_output_dir):
        """Should work with --no-logp."""
        out = os.path.join(tmp_output_dir, "qq_raw.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--no-logp",
        ])
        assert rc == 0

    def test_no_abline(self, tmp_output_dir):
        """Should disable reference line with --ablinecolor none."""
        out = os.path.join(tmp_output_dir, "qq_noab.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--ablinecolor", "none",
        ])
        assert rc == 0

    def test_custom_marker_and_color(self, tmp_output_dir):
        """Should accept custom marker and color."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--marker", "s",
            "--color", "blue",
        ])
        assert rc == 0

    def test_custom_figsize(self, tmp_output_dir):
        """Should accept custom figure size."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--figsize", "8", "8",
        ])
        assert rc == 0

    def test_default_output_name(self, tmp_output_dir):
        """Should default to qq.png when -o is not given."""
        original_dir = os.getcwd()
        os.chdir(tmp_output_dir)
        try:
            rc = main(["qq", "-i", _GWAS_FILE])
            assert rc == 0
            assert os.path.isfile(os.path.join(tmp_output_dir, "qq.png"))
        finally:
            os.chdir(original_dir)

    def test_invalid_input_file(self, tmp_output_dir):
        """Should return error for non-existent input file."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main(["qq", "-i", "nonexistent_file.tsv", "-o", out])
        assert rc == 1

    def test_missing_pv_column(self, tmp_output_dir):
        """Should return error when p-value column doesn't exist."""
        out = os.path.join(tmp_output_dir, "qq.png")
        rc = main([
            "qq", "-i", _GWAS_FILE, "-o", out,
            "--pv", "NONEXISTENT_COL",
        ])
        assert rc == 1

    def test_missing_input_flag(self):
        """Should fail when -i is not provided."""
        with pytest.raises(SystemExit):
            main(["qq"])


# ===========================================================================
# Tests for the venn subcommand
# ===========================================================================
class TestVennCLI:
    """Tests for the ``geneview venn`` CLI subcommand."""

    @pytest.fixture(autouse=True)
    def _check_data(self):
        """Skip if test data is not available."""
        if not all(os.path.isfile(f) for f in _VENN_FILES):
            pytest.skip("Test Venn data not found in %s" % _VENN_DIR)

    def test_basic_2_sets(self, tmp_output_dir):
        """Should create a 2-set Venn diagram."""
        out = os.path.join(tmp_output_dir, "venn2.png")
        rc = main(["venn", "-i", _VENN_FILES[0], _VENN_FILES[1], "-o", out])
        assert rc == 0
        assert os.path.isfile(out)

    def test_basic_3_sets(self, tmp_output_dir):
        """Should create a 3-set Venn diagram."""
        out = os.path.join(tmp_output_dir, "venn3.png")
        rc = main(["venn", "-i"] + _VENN_FILES + ["-o", out])
        assert rc == 0
        assert os.path.isfile(out)

    def test_custom_names(self, tmp_output_dir):
        """Should accept custom dataset names."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--names", "Alpha", "Beta",
        ])
        assert rc == 0

    def test_custom_palette(self, tmp_output_dir):
        """Should accept custom palette."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--palette", "plasma",
        ])
        assert rc == 0

    def test_custom_fmt(self, tmp_output_dir):
        """Should accept custom format string for petal labels."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--fmt", "{size}\n({percentage:.0f}%)",
        ])
        assert rc == 0

    def test_legend_use_petal_color(self, tmp_output_dir):
        """Should accept --legend-use-petal-color flag."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--legend-use-petal-color",
        ])
        assert rc == 0

    def test_legend_loc(self, tmp_output_dir):
        """Should accept --legend-loc argument."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--legend-loc", "upper left",
        ])
        assert rc == 0

    def test_too_few_files(self, tmp_output_dir):
        """Should fail with fewer than 2 input files."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main(["venn", "-i", _VENN_FILES[0], "-o", out])
        assert rc == 1

    def test_nonexistent_file(self, tmp_output_dir):
        """Should fail for non-existent input files."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], "nonexistent.txt",
            "-o", out,
        ])
        assert rc == 1

    def test_default_output_name(self, tmp_output_dir):
        """Should default to venn.png when -o is not given."""
        original_dir = os.getcwd()
        os.chdir(tmp_output_dir)
        try:
            rc = main(["venn", "-i", _VENN_FILES[0], _VENN_FILES[1]])
            assert rc == 0
            assert os.path.isfile(os.path.join(tmp_output_dir, "venn.png"))
        finally:
            os.chdir(original_dir)

    def test_missing_input_flag(self):
        """Should fail when -i is not provided."""
        with pytest.raises(SystemExit):
            main(["venn"])

    def test_custom_fontsize_and_alpha(self, tmp_output_dir):
        """Should accept custom fontsize and alpha."""
        out = os.path.join(tmp_output_dir, "venn.png")
        rc = main([
            "venn", "-i", _VENN_FILES[0], _VENN_FILES[1],
            "-o", out,
            "--fontsize", "16",
            "--alpha", "0.6",
        ])
        assert rc == 0


# ===========================================================================
# Tests for the admixture subcommand
# ===========================================================================
class TestAdmixtureCLI:
    """Tests for the ``geneview admixture`` CLI subcommand."""

    @pytest.fixture(autouse=True)
    def _check_data(self):
        """Skip if test data is not available."""
        if not os.path.isfile(_ADMIXTURE_Q) or not os.path.isfile(_ADMIXTURE_POP):
            pytest.skip("Test admixture data not found in %s" % _ADMIXTURE_DIR)

    def test_basic_run(self, tmp_output_dir):
        """Should create an admixture plot with minimal arguments."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
        ])
        assert rc == 0
        assert os.path.isfile(out)

    def test_custom_palette(self, tmp_output_dir):
        """Should accept a custom palette."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--palette", "Set1",
        ])
        assert rc == 0

    def test_group_order(self, tmp_output_dir):
        """Should accept a custom group order."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--group-order", "POP4", "POP3", "POP2", "POP1",
        ])
        assert rc == 0

    def test_set_xticklabel_top(self, tmp_output_dir):
        """Should place labels at top with --set-xticklabel-top."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--set-xticklabel-top",
        ])
        assert rc == 0

    def test_xtick_rotation(self, tmp_output_dir):
        """Should accept x-tick label rotation."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--xtick-rotation", "45",
        ])
        assert rc == 0

    def test_edgewidth_and_linewidth(self, tmp_output_dir):
        """Should accept custom edge and line widths."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--edgewidth", "2.0",
            "--linewidth", "0.5",
        ])
        assert rc == 0

    def test_shuffle_frac(self, tmp_output_dir):
        """Should sample a fraction of each population."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--shuffle-frac", "0.5",
        ])
        assert rc == 0

    def test_shuffle_n(self, tmp_output_dir):
        """Should sample N individuals per population."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--shuffle-n", "10",
        ])
        assert rc == 0

    def test_custom_ylabel(self, tmp_output_dir):
        """Should accept a custom y-axis label."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--ylabel", "K=3 custom",
        ])
        assert rc == 0

    def test_default_output_name(self, tmp_output_dir):
        """Should default to admixture.png when -o is not given."""
        original_dir = os.getcwd()
        os.chdir(tmp_output_dir)
        try:
            rc = main([
                "admixture", "-i", _ADMIXTURE_Q,
                "-p", _ADMIXTURE_POP,
            ])
            assert rc == 0
            assert os.path.isfile(os.path.join(tmp_output_dir, "admixture.png"))
        finally:
            os.chdir(original_dir)

    def test_invalid_input_file(self, tmp_output_dir):
        """Should return error for non-existent input file."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", "nonexistent.Q",
            "-p", _ADMIXTURE_POP, "-o", out,
        ])
        assert rc == 1

    def test_missing_required_flags(self):
        """Should fail when required flags are missing."""
        with pytest.raises(SystemExit):
            main(["admixture"])
        with pytest.raises(SystemExit):
            main(["admixture", "-i", _ADMIXTURE_Q])
        with pytest.raises(SystemExit):
            main(["admixture", "-p", _ADMIXTURE_POP])

    def test_custom_figsize(self, tmp_output_dir):
        """Should accept custom figure size."""
        out = os.path.join(tmp_output_dir, "admixture.png")
        rc = main([
            "admixture", "-i", _ADMIXTURE_Q,
            "-p", _ADMIXTURE_POP, "-o", out,
            "--figsize", "16", "3",
        ])
        assert rc == 0
