"""Basic genome tracks introduction -- GenomeAxisTrack + AnnotationTrack.

This script demonstrates the fundamental concepts of geneview's genome tracks
module: creating track objects and combining them with plot_tracks().

Mirrors the Gviz vignette "Basic Features" section.

Run:  python examples/scripts/genome_tracks_basic.py
"""
import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import geneview as gv
from geneview.genometracks import (
    GenomeAxisTrack, AnnotationTrack, GenomicInterval, plot_tracks, read_bed,
)

# ---------------------------------------------------------------------------
# Locate example data (generated by generate_genome_tracks_data.py)
# ---------------------------------------------------------------------------
DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "genome_tracks")
BED_FILE = os.path.join(DATA_DIR, "cpg_islands.bed")

# ---------------------------------------------------------------------------
# 1. Create a simple AnnotationTrack from a BED file
# ---------------------------------------------------------------------------
cpg_data = read_bed(BED_FILE)
atrack = AnnotationTrack(cpg_data, name="CpG Islands", stacking="squish")

# ---------------------------------------------------------------------------
# 2. Add a GenomeAxisTrack for coordinate reference
# ---------------------------------------------------------------------------
gtrack = GenomeAxisTrack()

# ---------------------------------------------------------------------------
# 3. Define the genomic region to display
# ---------------------------------------------------------------------------
region = GenomicInterval("chr7", 26_500_000, 26_800_000)

# ---------------------------------------------------------------------------
# 4. Plot!  -- plot_tracks() is the single entry point for all track rendering
# ---------------------------------------------------------------------------
axes = plot_tracks(
    [gtrack, atrack],
    region=region,
    title="Basic Genome Tracks",
    figsize=(12, 4),
)
fig = axes[0].figure

out_path = os.path.join(os.path.dirname(__file__), "..", "figures",
                        "genome_tracks_basic.png")
os.makedirs(os.path.dirname(out_path), exist_ok=True)
fig.savefig(out_path, dpi=150, bbox_inches="tight")
print(f"[INFO] Saved figure to {out_path}")
plt.show()
