name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PYTHON: "3.8"
  NB_KERNEL: python
  MPLBACKEND: Agg

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7.x, 3.8.x, 3.9.x, 3.10.x]
        target: [test]
        backend: [agg]

        include:
          - python: 3.7.x
            target: unittests
            backend: agg
          - python: 3.9.x
            target: unittests
            backend: agg
          - python: 3.10.x
            target: unittests
            backend: agg
          - python: 3.9.x
            target: test
            backend: tkagg

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install geneview
        run: |
          python -m pip install --upgrade pip
          # Install geneview and test module
          pip install .[all] -r ci/utils.txt

      - name: Cache datasets
        run: python ci/cache_test_datasets.py

      - name: Run tests
        env:
          MPLBACKEND: ${{ matrix.backend }}
        run: |
          if [[ ${{ matrix.backend }} == "tkagg" ]]; then PREFIX="xvfb-run -a"; fi
          $PREFIX make ${{ matrix.target }}

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        if: ${{ success() }}
